USE PITANGHSU;
CREATE TABLE TRAIN (
TRAIN_NO INT primary KEY,
NAME varchar(50),
SOURCE varchar(50),
DESTINATION varchar(50)
);
insert INTO TRAIN (TRAIN_NO, NAME, SOURCE, DESTINATION)
values
(12001, 'RAJDHANI', 'DELHI', 'KOLKATA'),
(12002, 'SHATABDI', 'DELHI', 'BHOPAL'),
(12003, 'DURONTO', 'MUMBAI', 'DELHI'),
(12004, 'GARIB RATH', 'PATNA', 'DELHI'),
(12005, 'HOWRAH EXP', 'KOLKATA', 'CHENNAI'),
(12006, 'TEJAS', 'DELHI', 'LUCKNOW'),
(12007, 'INTER CITY', 'AGRA', 'DELHI'),
(12008, 'JAN SHATABDI', 'BHUBANESWAR', 'KOLKATA'),
(12009, 'EXPRESS', 'PUNE', 'MUMBAI'),
(12010, 'MAIL', 'JAYPUR', 'DELHI');