USE PITANGHSU;
SELECT * FROM EMPLOYEE
WHERE DEPT = 'IT';

SELECT * FROM EMPLOYEE
ORDER BY SALARY DESC LIMIT 1;

SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEE;

SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEE;