USE PITANGHSU;
SELECT * FROM BANK_ACCOUNT
where BALANCE < 5000;

SELECT SUM(BALANCE) AS TOTAL_BANK_BALANCE FROM BANK_ACCOUNT;

select * FROM BANK_ACCOUNT
ORDER BY BALANCE DESC LIMIT 1;

SELECT COUNT(*) AS TOTAL_ACCOUNTS_HOLDERS FROM BANK_ACCOUNT;